services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - rpg-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    ports:
      - '8080:80'
    networks:
      - rpg-network
    depends_on:
      - mysql
    
  backend:
    container_name: backend_rpg
    build:
      context: ./backend
      dockerfile: Dockerfile
    
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./backend/:/src/
    networks:
      - rpg-network
    depends_on:
      - mysql

networks:
  rpg-network:
    driver: bridge

volumes:
  mysql-data:
