name: Hello World Workflow

on:
  push:
    branches:
      - main # Pode ser qualquer branch que desejar
  pull_request:
    branches:
      - main # Pode ser qualquer branch que desejar

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello World"
